language: python

sudo: required

services:
  - docker

before_install:
  - docker pull centos:6
  - docker pull debian:6

script:
  - >
    docker run -v $(pwd):/var/tmp debian:6 bash -c
    "cd /var/tmp && apt-get update &&
     apt-get install  -y make dpkg-dev debhelper python-dev python-setuptools &&
     make deb"
  - >
    docker run -v $(pwd):/var/tmp centos:6 bash -c
    "cd /var/tmp &&
     yum install make rpm-build python2-devel python-setuptools &&
     make rpm"
