language: python

sudo: required

services:
  - docker

before_install:
  - docker pull centos:6
  - docker pull debian:7

script:
- docker run -v $(pwd):/var/tmp centos:6 /var/tmp/tests/centos.sh
- docker run -v $(pwd):/var/tmp debian:7 /var/tmp/tests/debian.sh
